# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='\u041b\u043e\u0433\u0438\u043d')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('email_approved', models.BooleanField(default=False, verbose_name='\u0418\u043c\u0435\u0439\u043b \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('second_name', models.CharField(blank=True, max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='\u0428\u043a\u043e\u043b\u0430')),
                ('is_active', models.BooleanField(default=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043e'), (1, '\u041c\u0443\u0436\u0447\u0438\u043d\u0430'), (2, '\u0416\u0435\u043d\u0449\u0438\u043d\u0430')], default=0, verbose_name='\u041f\u043e\u043b')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
