# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='\u041b\u043e\u0433\u0438\u043d')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('email_approved', models.BooleanField(default=False, verbose_name='\u0418\u043c\u0435\u0439\u043b \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('second_name', models.CharField(blank=True, max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='\u0428\u043a\u043e\u043b\u0430')),
                ('is_active', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043e'), (1, '\u041c\u0443\u0436\u0447\u0438\u043d\u0430'), (2, '\u0416\u0435\u043d\u0449\u0438\u043d\u0430')], default=0, verbose_name='\u041f\u043e\u043b')),
                ('approved', models.BooleanField(default=False)),
                ('city', models.SmallIntegerField(choices=[(0, '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043e'), (1, '\u0410\u043b\u043c\u0430\u0442\u044b'), (2, '\u0410\u0441\u0442\u0430\u043d\u0430'), (3, '\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430'), (4, '\u0428\u044b\u043c\u043a\u0435\u043d\u0442'), (5, '\u0422\u0430\u0440\u0430\u0437'), (6, '\u0410\u043a\u0442\u043e\u0431\u0435'), (7, '\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439'), (8, '\u0410\u043a\u0442\u0430\u0443'), (9, '\u0410\u0442\u044b\u0440\u0430\u0443'), (10, '\u0423\u0440\u0430\u043b\u044c\u0441\u043a'), (11, '\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440'), (12, '\u0423\u0441\u043a\u0430\u043c\u0430\u043d'), (13, '\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443'), (14, '\u0422\u0430\u043b\u0434\u044b\u043a'), (15, '\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b'), (16, '\u0421\u0435\u043c\u0435\u0439'), (17, '\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430'), (18, '\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d')], default=0, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0438\u0433\u0440\u044b')),
                ('status', models.SmallIntegerField(choices=[(0, '\u041d\u0435 \u043d\u0430\u0447\u0430\u043b\u0430\u0441\u044c'), (1, '\u041d\u0430\u0447\u0430\u043b\u0430\u0441\u044c'), (2, '\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0438\u0433\u0440\u044b')),
                ('shuffled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u0438\u0433\u0440\u044b')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0438\u0433\u0440\u044b')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.SmallIntegerField(default=0, verbose_name='\u0423\u0431\u0438\u0439\u0441\u0442\u0432')),
                ('approved', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u0435\u043a\u0440\u0435\u0442\u043d\u044b\u0439 \u043a\u043b\u044e\u0447')),
                ('status', models.SmallIntegerField(choices=[(0, '\u0416\u0438\u0432'), (1, '\u0423\u0431\u0438\u0442')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_entries', to='main.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_entries', to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim_game_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KillLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killer_logs', to=settings.AUTH_USER_MODEL, verbose_name='\u0423\u0431\u0438\u0439\u0446\u0430')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_logs', to=settings.AUTH_USER_MODEL, verbose_name='\u0416\u0435\u0440\u0442\u0432\u0430')),
            ],
        ),
    ]
