# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u041b\u043e\u0433\u0438\u043d'),
        ),
    ]
