# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0438\u0433\u0440\u044b')),
                ('status', models.SmallIntegerField(choices=[(0, '\u041d\u0435 \u043d\u0430\u0447\u0430\u043b\u0430\u0441\u044c'), (1, '\u041d\u0430\u0447\u0430\u043b\u0430\u0441\u044c'), (2, '\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0438\u0433\u0440\u044b')),
                ('shuffled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u0438\u0433\u0440\u044b')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0438\u0433\u0440\u044b')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.SmallIntegerField(default=0, verbose_name='\u0423\u0431\u0438\u0439\u0441\u0442\u0432')),
                ('approved', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u0435\u043a\u0440\u0435\u0442\u043d\u044b\u0439 \u043a\u043b\u044e\u0447')),
                ('status', models.SmallIntegerField(choices=[(0, '\u0416\u0438\u0432'), (1, '\u0423\u0431\u0438\u0442')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_entries', to='main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='KillLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
            ],
        ),
        migrations.AddField(
            model_name='mainuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='city',
            field=models.SmallIntegerField(choices=[(0, '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043e'), (1, '\u0410\u043b\u043c\u0430\u0442\u044b'), (2, '\u0410\u0441\u0442\u0430\u043d\u0430'), (3, '\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430'), (4, '\u0428\u044b\u043c\u043a\u0435\u043d\u0442'), (5, '\u0422\u0430\u0440\u0430\u0437'), (6, '\u0410\u043a\u0442\u043e\u0431\u0435'), (7, '\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439'), (8, '\u0410\u043a\u0442\u0430\u0443'), (9, '\u0410\u0442\u044b\u0440\u0430\u0443'), (10, '\u0423\u0440\u0430\u043b\u044c\u0441\u043a'), (11, '\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440'), (12, '\u0423\u0441\u043a\u0430\u043c\u0430\u043d'), (13, '\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443'), (14, '\u0422\u0430\u043b\u0434\u044b\u043a'), (15, '\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b'), (16, '\u0421\u0435\u043c\u0435\u0439'), (17, '\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430'), (18, '\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d')], default=0, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='user_name',
            field=models.CharField(db_index=True, max_length=9, unique=True, verbose_name='\u041b\u043e\u0433\u0438\u043d'),
        ),
        migrations.AddField(
            model_name='killlog',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killer_logs', to=settings.AUTH_USER_MODEL, verbose_name='\u0423\u0431\u0438\u0439\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='killlog',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_logs', to=settings.AUTH_USER_MODEL, verbose_name='\u0416\u0435\u0440\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim_game_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
