# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160912_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
