# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161019_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='faculty',
            field=models.SmallIntegerField(choices=[(0, '\u0424\u0418\u0422'), (1, '\u0411\u0428'), (2, '\u0424\u0415\u041d\u0413\u0418'), (3, '\u041c\u0428\u042d')], default=4, verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
