# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161019_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
