# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161020_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='gameentry',
            unique_together=set([('game', 'player')]),
        ),
    ]
