# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161021_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameentry',
            options={'verbose_name_plural': 'Game Entries'},
        ),
    ]
