# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161021_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='course',
            field=models.SmallIntegerField(choices=[(1, '\u041f\u0435\u0440\u0432\u044b\u0439'), (2, '\u0412\u0442\u043e\u0440\u043e\u0439'), (3, '\u0422\u0440\u0435\u0442\u0438\u0439'), (4, '\u0427\u0435\u0442\u0432\u0435\u0440\u0442\u044b\u0439'), (5, '\u041f\u044f\u0442\u044b\u0439')], default=1, verbose_name='\u041a\u0443\u0440\u0441'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='faculty',
            field=models.SmallIntegerField(choices=[(0, '\u0424\u0418\u0422'), (1, '\u0411\u0428'), (2, '\u0424\u042d\u041d\u0413\u0418'), (3, '\u041c\u0428\u042d'), (5, '\u041a\u041c\u0410'), (6, '\u0425\u0422\u041e\u0412'), (7, '\u041c\u041a\u041c')], default=4, verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442'),
        ),
    ]
