# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainuser_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameentry',
            name='status',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '\u0416\u0438\u0432'), (1, '\u0423\u0431\u0438\u0442')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
