# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171015_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e'),
        ),
    ]
