# -*- coding: utf-8 -*-
OK = 0
MISSING_PARAMETER = 1
WRONG_SECRET_KEY = 2
AUTHENTIFICATION_FAILED = 3
INVALID_FORM = 4
SUCCESS_REGISTRATION = 5
INVALID_USER = 6
SUCCESS_KILL = 7
NOT_GOOD_SECRET_KEY = 8
ERROR_OLD_PASS = 9
PASSWORDS_DONT_MATCH = 10
SUCCESS = 11
NOT_LOGGED_IN = 12
SERVER_ERROR = 500